//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anamnese
    {
        public int idAnamnese { get; set; }
        public int idMatricula { get; set; }
        public System.DateTime DtAnamnese { get; set; }
        public string QP { get; set; }
        public string HM { get; set; }
        public string Esporte { get; set; }
        public string PosicaoQueDorme { get; set; }
        public string Humor { get; set; }
        public string Dor { get; set; }
        public string DescricaoDor { get; set; }
        public string DiagnosticoMedico { get; set; }
        public string Medicacao { get; set; }
        public string Patologias { get; set; }
    
        public virtual Matricula Matricula { get; set; }
    }
}
