//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleto
    {
        public int idBoleto { get; set; }
        public int idMatricula { get; set; }
        public Nullable<double> Desconto { get; set; }
        public double ValorTotal { get; set; }
        public System.DateTime DtPagamento { get; set; }
        public string FormaDePagamento { get; set; }
    
        public virtual Matricula Matricula { get; set; }
    }
}
