//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frequencia
    {
        public int idFrequencia { get; set; }
        public int idMatricula { get; set; }
        public int idTurma { get; set; }
        public Nullable<System.DateTime> DtDia { get; set; }
    
        public virtual Matricula Matricula { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
