//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matricula()
        {
            this.Anamnese = new HashSet<Anamnese>();
            this.Boleto = new HashSet<Boleto>();
        }
    
        public int idMatricula { get; set; }
        public string CPF { get; set; }
        public int idTurma { get; set; }
        public string TipoPlano { get; set; }
        public double ValorMensal { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
        public bool SituacaoMatricula { get; set; }
        public int QtdeAulas { get; set; }
        public Nullable<int> idTurma2 { get; set; }
        public Nullable<int> idTurma3 { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anamnese> Anamnese { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleto> Boleto { get; set; }
        public virtual Turma Turma { get; set; }
        public virtual Turma Turma1 { get; set; }
        public virtual Turma Turma2 { get; set; }
    }
}
